export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const LOAD_PLAYERS_SUCCESS = "LOAD_PLAYERS_SUCCESS";
export const CREATE_PLAYER = "CREATE_PLAYER";
export const CREATE_PLAYER_SUCCESS = "CREATE_PLAYER_SUCCESS";
export const UPDATE_PLAYER_SUCCESS = "UPDATE_PLAYER_SUCCESS";
export const DELETE_PLAYER_SUCCESS = "DELETE_PLAYER_SUCCESS";

export const LOAD_COUNTRIES_SUCCESS = "LOAD_COUNTRIES_SUCCESS";
